const Icons = {
    Home : require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/Home.png'),
    Account: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/Account.png'),
    Fav: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/Fav.png'),
    Menu: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/Menu.png'),
    BackIcon: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/BackIcon.png'),
    Notifications: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/Notifications.png'),
    SearchIcon: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/SearchIcon.png'),
    AddPhone: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/AddPhone.png'),
    BackIconWhite: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/BackIconWhite.png'),
    VerticalThreeDots: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/VerticalthreeDot.png'),
    eyeIcon: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/eyeIcon.png'),
    deleteIcon: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/deleteIcon.png'),
    pinIcon: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/pinIcon.png'),
    send: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/send.png'),
    addPhone: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/AddPhone.png'),
    like: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/like.png'),
    dislike: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/dislike.png'),
    love:require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/love.png'),
    laugh: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/laugh.png'),
    celebration: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/celebratation.png'),
    cross: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/close.png'),
    pin: require('/Users/admin/Desktop/BottomTabBar/src/assests/icons/pin.png'),
};
export {Icons};